[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dex_test = "B8bLbeEf2bhsjqktMmuabfgA4GmByDuY9WRvzuc7cY72"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://dark-intensive-dream.solana-mainnet.quiknode.pro/bcea36be83c7f3b3e1afbb625fa47048926bf67f/"
wallet = "/Users/jason404/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
